create VIEW vairReferencedomainAA  
as      
SELECT       
(      
select      
DISTINCT    
RD.GUID as '_id.$oid',      
CASE WHEN RD.DOMAINCODE='PBMCD' THEN 'COMORB'    
WHEN RD.DOMAINCODE='FORMM' THEN 'DGFORM'    
WHEN RD.DOMAINCODE='ROUTE' THEN 'ROUTE'    
WHEN RD.DOMAINCODE='ESDRGTP' THEN 'ESSNDG'    
WHEN RD.DOMAINCODE='SLCTP' THEN 'FOLDTY'    
WHEN RD.DOMAINCODE='TITLE' THEN 'TITLE'    
WHEN RD.DOMAINCODE='NATNL' THEN 'NATNTY'    
WHEN RD.DOMAINCODE='BLOOD' THEN 'BLDGRP'    
WHEN RD.DOMAINCODE='BLDRH' THEN 'RHFACT'    
WHEN RD.DOMAINCODE='SPOKL' THEN 'PRFLAN'    
WHEN RD.DOMAINCODE='OCCUP' THEN 'OCCUPN'    
WHEN RD.DOMAINCODE='RELTN' THEN 'NOKTYP'    
WHEN RD.DOMAINCODE='RLNTP' THEN 'NOKTYP'    
WHEN RD.DOMAINCODE='PAALI' THEN 'ALSTYP'    
WHEN RD.DOMAINCODE='PITYP' THEN 'IDTYPE'    
WHEN RD.DOMAINCODE='RAACE' THEN 'RACE'    
WHEN RD.DOMAINCODE='MARRY' THEN 'MARTST'    
WHEN RD.DOMAINCODE='RELGN' THEN 'RELGON'    
WHEN RD.DOMAINCODE='ADTYP' THEN 'ADRTYP'    
WHEN RD.DOMAINCODE='VISTY' THEN 'VSTTYP'    
WHEN RD.DOMAINCODE='BKMOD' THEN 'BOKMOD'    
WHEN RD.DOMAINCODE='RFRTP' THEN 'REFTYP'    
WHEN RD.DOMAINCODE='CPTYP' THEN 'PROVIDERTYPE'    
WHEN RD.DOMAINCODE='MDTRN' THEN 'TRNSMD'    
WHEN RD.DOMAINCODE='CANRE' THEN 'CANRSN'    
WHEN RD.DOMAINCODE='MDTRN' THEN 'TRNSPT'    
WHEN RD.DOMAINCODE='DSOCM' THEN 'PATST'    
WHEN RD.DOMAINCODE='SPMTP' THEN 'SPCMTY'    
WHEN RD.DOMAINCODE='COLMD' THEN 'COLMTD'    
WHEN RD.DOMAINCODE='MERUP' THEN 'MEMRPT'    
WHEN RD.DOMAINCODE='LRDELI' THEN 'DLVYMD'    
WHEN RD.DOMAINCODE='BDLOC' THEN 'BODYSI'    
WHEN RD.DOMAINCODE='BODST' THEN 'BODYSI'    
WHEN RD.DOMAINCODE='ABCAN' THEN 'ABCANL'    
WHEN RD.DOMAINCODE='VENAN' THEN 'VENANL'    
WHEN RD.DOMAINCODE='CRDTY' THEN 'CCTYPE'    
WHEN RD.DOMAINCODE='PAYMD' THEN 'PAYMOD'    
WHEN RD.DOMAINCODE='CURNC' THEN 'CURNCY'    
WHEN RD.DOMAINCODE='PYRACAT' THEN 'ARCATY'    
WHEN RD.DOMAINCODE='PBLCT' THEN 'TARIFF'    
WHEN RD.DOMAINCODE='PAYTRM' THEN 'CRDTRM'    
WHEN RD.DOMAINCODE='IMUOM' THEN 'INVUOM'    
WHEN RD.DOMAINCODE='RQPRT' THEN 'ORDPRY'    
WHEN RD.DOMAINCODE='INSTYP' THEN 'INSTYP'    
WHEN RD.DOMAINCODE='PRTGP' THEN 'RESGRP'    
WHEN RD.DOMAINCODE='PATTP' THEN 'PATTYP'    
WHEN RD.DOMAINCODE='NATNL' THEN 'NATNTY'    
WHEN RD.DOMAINCODE='DESTIN' THEN 'TRNSMD'    
WHEN RD.DOMAINCODE='BDCAT' THEN 'BEDCAT'    
WHEN RD.DOMAINCODE='VIPTP' THEN 'VIPTYP'    
WHEN RD.DOMAINCODE='SCDTY' THEN 'PDOCTY'    
WHEN RD.DOMAINCODE='REFNET' THEN 'REFTYP'    
WHEN RD.DOMAINCODE='REFCAT' THEN 'REFTYP'---refertype    
WHEN RD.DOMAINCODE='PDSTS' THEN 'DGTAKE'    
WHEN RD.DOMAINCODE='REFST' THEN 'REFSTS'    
WHEN RD.DOMAINCODE='REFSN' THEN 'REFREASON'    
WHEN RD.DOMAINCODE='EVATY' THEN 'REFEVATYP'    
WHEN RD.DOMAINCODE='RFRTP' THEN 'REFERRERTYP'    
WHEN RD.DOMAINCODE='EMPST' THEN 'EMPSTS'    
WHEN RD.DOMAINCODE='RPRIT' THEN 'VSTPRY'    
WHEN RD.DOMAINCODE='FILST' THEN 'FLDSTS'    
WHEN RD.DOMAINCODE='BKSTS' THEN 'BOKSTS'    
WHEN RD.DOMAINCODE='RIUOM' THEN 'OBSUOM'    
WHEN RD.DOMAINCODE='PRDCAT' THEN 'PRDCAT'    
WHEN RD.DOMAINCODE='LOTYP' THEN 'LOCTYP'  
WHEN RD.DOMAINCODE='SCHVAL' THEN 'CODISC'  
WHEN RD.DOMAINCODE='REQRSN' THEN 'FLDRQP'   
WHEN RD.DOMAINCODE='CONTP' THEN 'CONTYP'  
WHEN RD.DOMAINCODE='DSHTYP' THEN 'ERDTYP'  
WHEN RD.DOMAINCODE='DCSTS' THEN 'PATSTS'  
WHEN RD.DOMAINCODE='INFCT' THEN 'INFTYP'  
WHEN RD.DOMAINCODE='BSMDD' THEN 'SRCTY'  
WHEN RD.DOMAINCODE='NRCTP' THEN 'NRCDRG'  
WHEN RD.DOMAINCODE='RISCT' THEN 'ALRTYP'  
WHEN RD.DOMAINCODE='CMPTP' THEN 'PYRTYP'  
WHEN RD.DOMAINCODE='ALRGN' THEN 'DCODTY'  
WHEN RD.DOMAINCODE='AGUOM' THEN 'AGEGRP'  
  
END     code ,      
LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(      
              LTRIM(RTRIM(rd.Description)), CHAR(9), ' '), CHAR(10), ' '), CHAR(11), ' '), CHAR(12), ' '), CHAR(13), ' ')))description,      
     LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(      
              LTRIM(RTRIM(rd.Description)), CHAR(9), ' '), CHAR(10), ' '), CHAR(11), ' '), CHAR(12), ' '), CHAR(13), ' ')))name,      
CAST(cast(DATEDIFF_BIG(s, '1970-01-01 00:00:00.000', DATEADD(HH,-8,rD.ActiveFrom)) as bigint) * 1000  AS NVARCHAR(50))  'activefrom.$date.$numberLong',         
CAST(cast(DATEDIFF_BIG(s, '1970-01-01 00:00:00.000', dateadd(HH,-8,RD.ACTIVETO)) as bigint) * 1000  AS NVARCHAR(50))  'activeto.$date.$numberLong',      
isnull((SELECT TOP 1 GUID FROM CAREPROVIDER C WHERE C.UID=RD.CUSER),'5b862a913238d86bf03aa787') AS 'createdby.$oid',                               
CAST(cast(DATEDIFF_BIG(s, '1970-01-01 00:00:00.000', DATEADD(HH,-8,RD.CWHEN) ) as bigint) * 1000  AS NVARCHAR(50))  'createdat.$date.$numberLong',                                
isnull((SELECT TOP 1 GUID FROM CAREPROVIDER C WHERE C.UID=RD.MUSER),'5b862a913238d86bf03aa787') AS 'modifiedby.$oid',                          
CAST(cast(DATEDIFF_BIG(s, '1970-01-01 00:00:00.000', DATEADD(HH,-8,RD.mWHEN)) as bigint) * 1000  AS NVARCHAR(50)) 'modifiedat.$date.$numberLong',        
case when IsSortByDescription='Y' THEN convert(bit,'true') else convert(bit,'false') end sortbydescription,    
RD.STATUSFLAG statusflag,    
'BACKEND' Type,      
     
(      
SELECT distinct RF.GUID as '$oid' FROM ReferenceValue rf      
WHERE rf.STATUSFLAG='A'    
and RF.DOMAINCODE=rd.DomainCode for json path) as [values],      
rd.uid as externaluid      
from referencedomain rd     
where rd.domaincode  in('PBMCD','FORMM',    
'ROUTE','ESDRGTP','SLCTP','TITLE','NATNL','BLOOD','BLDRH','SPOKL','OCCUP','RLNTP','RELTN',    
'PAALI','PITYP','RAACE','MARRY','RELGN','ADTYP','VISTY','BKMOD','RFRTP','CPTYP','MDTRN','CANRE','MDTRN','DSOCM',    
'SPMTP','COLMD','MERUP','LRDELI','BODST','BDLOC','ABCAN','VENAN','CRDTY','PAYMD','CURNC','PYRACAT','PBLCT',    
'PAYTRM','IMUOM','RQPRT','INSTYP','PRTGP','PATTP','NATNL','DESTIN','BDCAT','VIPTP','REFNET','REFCAT','SCDTY','PDSTS','REFST',    
'REFSN','EVATY','RFRTP','EMPST','RPRIT','FILST','BKSTS','RIUOM','PRDCAT','LOTYP','SCHVAL','CONTP','DSHTYP','DCSTS','INFCT','BSMDD','NRCTP','RISCT','CMPTP','ALRGN','AGUOM')    
for json path)as x    